### Declare Vars

In [2]:
!pip install ortools


    0% |▎                               | 194kB 888kB/s eta 0:00:29^C

Operation cancelled by user


### Testing

In [1]:
from __future__ import print_function
import numpy as np
from time import time
from ortools.sat.python import cp_model
import itertools
import numpy as np

ImportError: No module named ortools.sat.python

In [3]:
model = cp_model.CpModel()

t = np.full(shape=(4, 3, 2), fill_value=0)

NameError: name 'cp_model' is not defined

In [35]:
t#.tolist()

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [55]:
t.size

24

In [41]:
model.NewIntVar(0,1, "23")

23(0..1)

In [44]:
for i_in in np.arange(10):
    print(i_in)

0
1
2
3
4
5
6
7
8
9


In [45]:
import itertools

In [50]:
list(itertools.chain('ABC','DEF'))

['A', 'B', 'C', 'D', 'E', 'F']

In [62]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
np.delete(a, 2, axis=1)

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

In [70]:
a = np.arange(24).reshape(4, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
np.delete(a, 2, axis=1)

In [92]:
itertools.chain(*a[:,:,:-1])

In [108]:
a[:,2,:1]

array([[ 4],
       [10],
       [16],
       [22]])

In [107]:
a[:][2][:1]

array([[12, 13]])

In [74]:
np.delete(a, 1, 2)

array([[[ 0],
        [ 2],
        [ 4]],

       [[ 6],
        [ 8],
        [10]],

       [[12],
        [14],
        [16]],

       [[18],
        [20],
        [22]]])

In [1]:
np.array([model.NewBoolVar("1"), model.NewBoolVar("2"), model.NewBoolVar("3")]).app

NameError: name 'np' is not defined